### ISSUE TITLE
建议提供一个截图或者在线 Demo 

### ISSUE THREAD

**Issue by YCF** [N3-components/N3-admin#1]
可能因为没有 Demo ，很多懒人连试一下的动机都没有。

**Comment by x-cold** [comment]
好的~ 谢谢建议

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: You Can FLy<mailto:notifications@github.com>
发送时间: 2017年2月26日 10:43
收件人: N3-components/N3-admin<mailto:N3-admin@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [N3-components/N3-admin] 建议提供一个截图或者在线 Demo (#1)


可能因为没有 Demo ，很多懒人连试一下的动机都没有。

―
