### ISSUE TITLE
项目规划

### ISSUE THREAD

**Issue by x-cold** [N3-components/N3-admin#2]
N3-admin 将构建成基于N3-components的后端管理系统模板及基本组件库。

由于本人近段时间工作较繁忙，开发工作将在3-5月陆续进行，欢迎提交建议~

**Comment by gitshancai** [comment]
运行后 在首页出现大量 [Vue warn]: Missing required prop: "index" nav 菜单显示不正常

**Comment by Dafrok** [comment]
说明你需要传一个 prop 进去
